seed: 42
device: "cuda"   # "cpu" if no GPU
data:
  root: "data/augmented_dataset"
  img_size: 224
  batch_size: 32
  num_workers: 4
train:
  epochs: 25
  lr: 0.0003
  weight_decay: 0.0001
  patience: 6
  model_name: "resnet50"  # or "resnet50" #resnet50_v2 #efficientnet_b0
log:
  out_dir: "outputs"

#3 diffrentrt lr 0.0001, 0.0005,0.00001
#learning rate decay
#data augmentation at the beginning
#y5e1tpu
